apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearn
  namespace: ravi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elearn
  template:
    metadata:
      labels:
        app: elearn
    spec:
      containers:
        - name: elearn
          image: acrbest.azurecr.io/elearnapp:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
